# Site settings
title: MDLware.io
email: 
description: > # this means to ignore newlines until "baseurl:"
  An exciting new BaaS solution, for POS, B2B and B2C sales. Launching Q4 2018
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"